# site settings
title: Nica YC Lin
subtitle: Personal Website
email: nicayclin@gmail.com
description: I also go by Nica!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nicalin.github.io" # the base hostname & protocol for your site
author: Nica
# street_address: 1234 Somewhere Road
city: Hsinchu
# state: TN
zip_code: 300
country: Taiwan
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/nicalin
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/nicayclin/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
